const APPLICATION_A_MAIN_EVENT = "APPLICATION_A_MAIN_EVENT";
const APPLICATION_B_MAIN_EVENT = "APPLICATION_B_MAIN_EVENT";
const APPLICATION_MAIN_EVENT = "APPLICATION_MAIN_EVENT";

const APPLICATION_REFRESH = "APPLICATION_REFRESH";
const APPLICATION_EXPIRE = "APPLICATION_EXPIRE";

const WARNING_IDLE_MILLISECONDS = 20 * 1000;
const EXPIRED_IDLE_MILLISECONDS = 30 * 1000;
